// lib/agents/FertilizerInterviewAgent.ts
import { BaseInterviewAgent, InterviewQuestion } from "./BaseInterviewAgent";

const plantingFertilizerOptions = [
  { value: "DAP (18-46-0)", label: "DAP (18-46-0)" },
  { value: "TSP (0-46-0)", label: "TSP (0-46-0)" },
  { value: "SSP (0-20-0)", label: "SSP (0-20-0)" },
  { value: "NPK 23-23-0 (23-23-0)", label: "NPK 23-23-0 (23-23-0)" },
  { value: "NPK 17-17-17 (17-17-17)", label: "NPK 17-17-17 (17-17-17)" },
  { value: "NPK 12.24.12+5S (12-24-12+5S)", label: "NPK 12.24.12+5S (12-24-12+5S)" },
  { value: "Yara Mila Power (13-24-12)", label: "Yara Mila Power (13-24-12)" },
  { value: "MEA NPK 10-26-10", label: "MEA NPK 10-26-10" },
  { value: "OCP NPSB (18.9-37.7-0)", label: "OCP NPSB (18.9-37.7-0)" },
  { value: "Other", label: "Other" },
];

const topdressingFertilizerOptions = [
  { value: "UREA (46-0-0)", label: "UREA (46-0-0)" },
  { value: "CAN (27-0-0)", label: "CAN (27-0-0)" },
  { value: "ASN (21-0-0-23S)", label: "ASN (21-0-0-23S)" },
  { value: "Yara Bela Sulfan (24-0-0+6S)", label: "Yara Bela Sulfan (24-0-0+6S)" },
  { value: "KynoKuza (20-4-20)", label: "KynoKuza (20-4-20)" },
  { value: "KynoGrowMax (30-0-10)", label: "KynoGrowMax (30-0-10)" },
  { value: "NPK 23-10-10", label: "NPK 23-10-10" },
  { value: "NPK 26-0-20", label: "NPK 26-0-20" },
  { value: "Other", label: "Other" },
];

const potassiumFertilizerOptions = [
  { value: "MOP (0-0-60)", label: "MOP (0-0-60)" },
  { value: "SOP (0-0-50)", label: "SOP (0-0-50)" },
  { value: "Korn-Kali (0-0-40)", label: "Korn-Kali (0-0-40)" },
  { value: "Patentkali (0-0-30)", label: "Patentkali (0-0-30)" },
  { value: "None - I don't use potassium", label: "None - I don't use potassium" },
];

const ratingOptions = [
  { value: "Very Low", label: "Very Low" },
  { value: "Low", label: "Low" },
  { value: "Optimum", label: "Optimum" },
  { value: "High", label: "High" },
  { value: "Very High", label: "Very High" },
];

export class FertilizerInterviewAgent extends BaseInterviewAgent {
  constructor() {
    super();
    this.questions = [
      // Gatekeeper
      {
        id: "hasDoneSoilTest",
        type: "select",
        label: "Have you done a soil test?",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
        ],
        required: true,
      },
      // ===== SOIL TEST DETAILS (depends on Yes) =====
      {
        id: "soilTestDate",
        type: "date",
        label: "When was the soil test done?",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestPH",
        type: "number",
        label: "What is the soil pH?",
        placeholder: "e.g., 6.5",
        step: "0.1",
        min: 0,
        max: 14,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestPHRating",
        type: "select",
        label: "Soil pH rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestP",
        type: "number",
        label: "Phosphorus (P) level (ppm)",
        placeholder: "e.g., 25",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestPRating",
        type: "select",
        label: "Phosphorus rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestK",
        type: "number",
        label: "Potassium (K) level (ppm)",
        placeholder: "e.g., 150",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestKRating",
        type: "select",
        label: "Potassium rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestNPercent",
        type: "number",
        label: "Total Nitrogen (N) %",
        placeholder: "e.g., 0.15",
        step: "0.01",
        min: 0,
        max: 5,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestNPercentRating",
        type: "select",
        label: "Nitrogen rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestCa",
        type: "number",
        label: "Calcium (Ca) level (ppm)",
        placeholder: "e.g., 800",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestCaRating",
        type: "select",
        label: "Calcium rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestMg",
        type: "number",
        label: "Magnesium (Mg) level (ppm)",
        placeholder: "e.g., 200",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestMgRating",
        type: "select",
        label: "Magnesium rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestNa",
        type: "number",
        label: "Sodium (Na) level (ppm)",
        placeholder: "e.g., 50",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestNaRating",
        type: "select",
        label: "Sodium rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestOC",
        type: "number",
        label: "Organic Carbon (OC) %",
        placeholder: "e.g., 1.2",
        step: "0.01",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestOCRating",
        type: "select",
        label: "Organic Carbon rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestOM",
        type: "number",
        label: "Organic Matter (OM) %",
        placeholder: "e.g., 2.5",
        step: "0.01",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestOMRating",
        type: "select",
        label: "Organic Matter rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestCEC",
        type: "number",
        label: "Cation Exchange Capacity (CEC)",
        placeholder: "e.g., 15",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "soilTestCECRating",
        type: "select",
        label: "CEC rating",
        options: ratingOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== TARGET YIELD & RECOMMENDATIONS =====
      {
        id: "targetYield",
        type: "number",
        label: "What is your target yield (kg per acre)?",
        placeholder: "e.g., 2000",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recCalciticLime",
        type: "number",
        label: "Recommended Calcitic Lime (kg/acre)",
        placeholder: "e.g., 120",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recDolomiticLime",
        type: "number",
        label: "Recommended Dolomitic Lime (kg/acre)",
        placeholder: "e.g., 120",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recPlantingFertilizer",
        type: "text",
        label: "Recommended Planting Fertilizer (from soil test)",
        placeholder: "e.g., NPK 12.24.12+5S",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recPlantingQuantity",
        type: "number",
        label: "Recommended Planting Fertilizer Quantity (kg/acre)",
        placeholder: "e.g., 100",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recTopdressingFertilizer",
        type: "text",
        label: "Recommended Topdressing Fertilizer (from soil test)",
        placeholder: "e.g., UREA 46-0-0",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recTopdressingQuantity",
        type: "number",
        label: "Recommended Topdressing Quantity (kg/acre)",
        placeholder: "e.g., 90",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recPotassiumFertilizer",
        type: "text",
        label: "Recommended Potassium Fertilizer (from soil test)",
        placeholder: "e.g., MOP 0-0-60",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "recPotassiumQuantity",
        type: "number",
        label: "Recommended Potassium Quantity (kg/acre)",
        placeholder: "e.g., 30",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== PLANTING FERTILIZER SELECTION =====
      {
        id: "plantingFertilizerToUse",
        type: "select",
        label: "Which planting fertilizer will you use?",
        options: plantingFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "plantingFertilizerCost",
        type: "number",
        label: "Cost of planting fertilizer (KES per 50kg bag)",
        placeholder: "e.g., 3500",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== TOPDRESSING FERTILIZER SELECTION =====
      {
        id: "topdressingFertilizerToUse",
        type: "select",
        label: "Which topdressing fertilizer will you use?",
        options: topdressingFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "topdressingFertilizerCost",
        type: "number",
        label: "Cost of topdressing fertilizer (KES per 50kg bag)",
        placeholder: "e.g., 2800",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== POTASSIUM FERTILIZER SELECTION =====
      {
        id: "potassiumFertilizerToUse",
        type: "select",
        label: "Which potassium fertilizer will you use?",
        options: potassiumFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "potassiumFertilizerCost",
        type: "number",
        label: "Cost of potassium fertilizer (KES per 50kg bag)",
        placeholder: "e.g., 2800",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== NUTRIENT DETAILS =====
      {
        id: "plantingFertilizerNutrients",
        type: "text",
        label: "Additional nutrients in planting fertilizer (e.g., S, Zn, etc.)",
        placeholder: "e.g., S 5%, Zn 1%",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "topdressingFertilizerNutrients",
        type: "text",
        label: "Additional nutrients in topdressing fertilizer",
        placeholder: "e.g., S 5%",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "potassiumFertilizerNutrients",
        type: "text",
        label: "Additional nutrients in potassium fertilizer",
        placeholder: "e.g., Mg 2%",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== LIME PRICES =====
      {
        id: "calciticLimePricePerBag",
        type: "number",
        label: "Price of Calcitic Lime per 50kg bag (KES)",
        placeholder: "e.g., 300",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      {
        id: "dolomiticLimePricePerBag",
        type: "number",
        label: "Price of Dolomitic Lime per 50kg bag (KES)",
        placeholder: "e.g., 300",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "Yes" },
      },
      // ===== EXTENSION OFFICER PATH (No soil test) =====
      {
        id: "plantingFertilizerType",
        type: "select",
        label: "What planting fertilizer do you use?",
        options: plantingFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
      {
        id: "plantingFertilizerQuantity",
        type: "number",
        label: "How many kg of planting fertilizer per acre?",
        placeholder: "e.g., 50",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
      {
        id: "topdressingFertilizerType",
        type: "select",
        label: "What topdressing fertilizer do you use?",
        options: topdressingFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
      {
        id: "topdressingFertilizerQuantity",
        type: "number",
        label: "How many kg of topdressing fertilizer per acre?",
        placeholder: "e.g., 50",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
      {
        id: "potassiumFertilizerType",
        type: "select",
        label: "What potassium fertilizer do you use?",
        options: potassiumFertilizerOptions,
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
      {
        id: "potassiumFertilizerQuantity",
        type: "number",
        label: "How many kg of potassium fertilizer per acre?",
        placeholder: "e.g., 50",
        step: "any",
        required: false,
        dependsOn: { field: "hasDoneSoilTest", value: "No" },
      },
    ];
  }

  async generateRecommendation(): Promise<any> {
    return {
      agentType: "FertilizerInterview",
      collectedData: this.answers,
      message: "Fertilizer details collected.",
    };
  }

  getAgentKey(): string {
    return this.constructor.name;
  }
}